/**
 * 英语音素数据（服务端配置）
 * 包含 44 个英语音素及对应的练习单词
 */

export interface PhonemeWord {
  word: string;
  phonetic: string;
  /** 目标音素在单词中的位置：beginning, middle, end */
  position: 'beginning' | 'middle' | 'end';
}

export interface MinimalPair {
  word1: string;      // 目标音素的词
  phonetic1: string;
  word2: string;      // 混淆音素的词
  phonetic2: string;
}

export interface Phoneme {
  /** 音素符号 (IPA) */
  symbol: string;
  /** 音素类型 */
  type: 'vowel' | 'consonant';
  /** 子类型 */
  subtype: 'short-vowel' | 'long-vowel' | 'diphthong' | 'voiced' | 'voiceless' | 'nasal' | 'liquid' | 'glide';
  /** 中文名称 */
  name: string;
  /** 发音描述/技巧 */
  description: string;
  /** 口型提示 */
  mouthTip: string;
  /** 常见错误 */
  commonMistakes: string[];
  /** 练习单词列表 */
  words: PhonemeWord[];
  /** 难度等级 1-5 */
  difficulty: number;
  /** 对于中国学习者的难度标记 */
  hardForChinese: boolean;
  /** 容易混淆的音素符号列表，按混淆程度排序 */
  confusableWith: string[];
  /** 最小对数据，key 为混淆音素符号 */
  minimalPairs?: Record<string, MinimalPair[]>;
}

export interface PhonemeCategory {
  id: string;
  name: string;
  description: string;
  phonemes: Phoneme[];
}

export const PHONEME_DATA_VERSION = 1;

// ============================================================================
// 元音 (Vowels) - 20个
// ============================================================================

const shortVowels: Phoneme[] = [
  {
    symbol: 'ɪ',
    type: 'vowel',
    subtype: 'short-vowel',
    name: '短元音 /ɪ/',
    description: '嘴唇微开，舌头靠前，发音短促',
    mouthTip: '嘴角微微向两边拉开，舌头放松',
    commonMistakes: ['容易发成长音 /iː/', '与中文"衣"混淆'],
    difficulty: 2,
    hardForChinese: true,
    confusableWith: ['iː', 'e'],
    minimalPairs: {
      'iː': [
        { word1: 'sit', phonetic1: '/sɪt/', word2: 'seat', phonetic2: '/siːt/' },
        { word1: 'ship', phonetic1: '/ʃɪp/', word2: 'sheep', phonetic2: '/ʃiːp/' },
        { word1: 'bit', phonetic1: '/bɪt/', word2: 'beat', phonetic2: '/biːt/' },
        { word1: 'fill', phonetic1: '/fɪl/', word2: 'feel', phonetic2: '/fiːl/' },
        { word1: 'hit', phonetic1: '/hɪt/', word2: 'heat', phonetic2: '/hiːt/' },
        { word1: 'lip', phonetic1: '/lɪp/', word2: 'leap', phonetic2: '/liːp/' },
        { word1: 'grin', phonetic1: '/ɡrɪn/', word2: 'green', phonetic2: '/ɡriːn/' },
        { word1: 'sin', phonetic1: '/sɪn/', word2: 'seen', phonetic2: '/siːn/' },
        { word1: 'till', phonetic1: '/tɪl/', word2: 'teal', phonetic2: '/tiːl/' },
        { word1: 'pill', phonetic1: '/pɪl/', word2: 'peel', phonetic2: '/piːl/' },
      ],
      'e': [
        { word1: 'sit', phonetic1: '/sɪt/', word2: 'set', phonetic2: '/set/' },
        { word1: 'pin', phonetic1: '/pɪn/', word2: 'pen', phonetic2: '/pen/' },
        { word1: 'bid', phonetic1: '/bɪd/', word2: 'bed', phonetic2: '/bed/' },
        { word1: 'tin', phonetic1: '/tɪn/', word2: 'ten', phonetic2: '/ten/' },
        { word1: 'lit', phonetic1: '/lɪt/', word2: 'let', phonetic2: '/let/' },
        { word1: 'did', phonetic1: '/dɪd/', word2: 'dead', phonetic2: '/ded/' },
        { word1: 'fill', phonetic1: '/fɪl/', word2: 'fell', phonetic2: '/fel/' },
        { word1: 'will', phonetic1: '/wɪl/', word2: 'well', phonetic2: '/wel/' },
        { word1: 'disk', phonetic1: '/dɪsk/', word2: 'desk', phonetic2: '/desk/' },
        { word1: 'miss', phonetic1: '/mɪs/', word2: 'mess', phonetic2: '/mes/' },
      ],
    },
    words: [
      { word: 'sit', phonetic: '/sɪt/', position: 'middle' },
      { word: 'big', phonetic: '/bɪɡ/', position: 'middle' },
      { word: 'fish', phonetic: '/fɪʃ/', position: 'middle' },
      { word: 'quick', phonetic: '/kwɪk/', position: 'middle' },
      { word: 'little', phonetic: '/ˈlɪtl/', position: 'beginning' },
    ],
  },
  {
    symbol: 'e',
    type: 'vowel',
    subtype: 'short-vowel',
    name: '短元音 /e/',
    description: '嘴唇半开，舌头中等高度',
    mouthTip: '嘴巴自然张开，比/ɪ/略大',
    commonMistakes: ['与/ɪ/混淆', '发音不够清晰'],
    difficulty: 2,
    hardForChinese: false,
    confusableWith: ['ɪ', 'æ'],
    minimalPairs: {
      'ɪ': [
        { word1: 'set', phonetic1: '/set/', word2: 'sit', phonetic2: '/sɪt/' },
        { word1: 'pen', phonetic1: '/pen/', word2: 'pin', phonetic2: '/pɪn/' },
        { word1: 'bed', phonetic1: '/bed/', word2: 'bid', phonetic2: '/bɪd/' },
        { word1: 'ten', phonetic1: '/ten/', word2: 'tin', phonetic2: '/tɪn/' },
        { word1: 'let', phonetic1: '/let/', word2: 'lit', phonetic2: '/lɪt/' },
        { word1: 'dead', phonetic1: '/ded/', word2: 'did', phonetic2: '/dɪd/' },
        { word1: 'fell', phonetic1: '/fel/', word2: 'fill', phonetic2: '/fɪl/' },
        { word1: 'well', phonetic1: '/wel/', word2: 'will', phonetic2: '/wɪl/' },
        { word1: 'desk', phonetic1: '/desk/', word2: 'disk', phonetic2: '/dɪsk/' },
        { word1: 'mess', phonetic1: '/mes/', word2: 'miss', phonetic2: '/mɪs/' },
      ],
      'æ': [
        { word1: 'bed', phonetic1: '/bed/', word2: 'bad', phonetic2: '/bæd/' },
        { word1: 'set', phonetic1: '/set/', word2: 'sat', phonetic2: '/sæt/' },
        { word1: 'pen', phonetic1: '/pen/', word2: 'pan', phonetic2: '/pæn/' },
        { word1: 'met', phonetic1: '/met/', word2: 'mat', phonetic2: '/mæt/' },
        { word1: 'head', phonetic1: '/hed/', word2: 'had', phonetic2: '/hæd/' },
        { word1: 'bet', phonetic1: '/bet/', word2: 'bat', phonetic2: '/bæt/' },
        { word1: 'men', phonetic1: '/men/', word2: 'man', phonetic2: '/mæn/' },
        { word1: 'red', phonetic1: '/red/', word2: 'rad', phonetic2: '/ræd/' },
        { word1: 'lend', phonetic1: '/lend/', word2: 'land', phonetic2: '/lænd/' },
        { word1: 'den', phonetic1: '/den/', word2: 'Dan', phonetic2: '/dæn/' },
      ],
    },
    words: [
      { word: 'bed', phonetic: '/bed/', position: 'middle' },
      { word: 'red', phonetic: '/red/', position: 'middle' },
      { word: 'pen', phonetic: '/pen/', position: 'middle' },
      { word: 'best', phonetic: '/best/', position: 'middle' },
      { word: 'every', phonetic: '/ˈevri/', position: 'beginning' },
    ],
  },
  {
    symbol: 'æ',
    type: 'vowel',
    subtype: 'short-vowel',
    name: '短元音 /æ/',
    description: '嘴巴张大，舌头平放，嘴角向两边拉',
    mouthTip: '嘴巴要张大，像微笑一样拉开嘴角',
    commonMistakes: ['容易发成/e/', '嘴巴张得不够大'],
    difficulty: 3,
    hardForChinese: true,
    confusableWith: ['e', 'ʌ'],
    minimalPairs: {
      'e': [
        { word1: 'bad', phonetic1: '/bæd/', word2: 'bed', phonetic2: '/bed/' },
        { word1: 'sat', phonetic1: '/sæt/', word2: 'set', phonetic2: '/set/' },
        { word1: 'pan', phonetic1: '/pæn/', word2: 'pen', phonetic2: '/pen/' },
        { word1: 'mat', phonetic1: '/mæt/', word2: 'met', phonetic2: '/met/' },
        { word1: 'had', phonetic1: '/hæd/', word2: 'head', phonetic2: '/hed/' },
        { word1: 'bat', phonetic1: '/bæt/', word2: 'bet', phonetic2: '/bet/' },
        { word1: 'man', phonetic1: '/mæn/', word2: 'men', phonetic2: '/men/' },
        { word1: 'rad', phonetic1: '/ræd/', word2: 'red', phonetic2: '/red/' },
        { word1: 'land', phonetic1: '/lænd/', word2: 'lend', phonetic2: '/lend/' },
        { word1: 'Dan', phonetic1: '/dæn/', word2: 'den', phonetic2: '/den/' },
      ],
      'ʌ': [
        { word1: 'bat', phonetic1: '/bæt/', word2: 'but', phonetic2: '/bʌt/' },
        { word1: 'cap', phonetic1: '/kæp/', word2: 'cup', phonetic2: '/kʌp/' },
        { word1: 'ran', phonetic1: '/ræn/', word2: 'run', phonetic2: '/rʌn/' },
        { word1: 'cat', phonetic1: '/kæt/', word2: 'cut', phonetic2: '/kʌt/' },
        { word1: 'bag', phonetic1: '/bæɡ/', word2: 'bug', phonetic2: '/bʌɡ/' },
        { word1: 'hat', phonetic1: '/hæt/', word2: 'hut', phonetic2: '/hʌt/' },
        { word1: 'match', phonetic1: '/mætʃ/', word2: 'much', phonetic2: '/mʌtʃ/' },
        { word1: 'sang', phonetic1: '/sæŋ/', word2: 'sung', phonetic2: '/sʌŋ/' },
      ],
    },
    words: [
      { word: 'cat', phonetic: '/kæt/', position: 'middle' },
      { word: 'bad', phonetic: '/bæd/', position: 'middle' },
      { word: 'apple', phonetic: '/ˈæpl/', position: 'beginning' },
      { word: 'happy', phonetic: '/ˈhæpi/', position: 'middle' },
      { word: 'black', phonetic: '/blæk/', position: 'middle' },
    ],
  },
  {
    symbol: 'ʌ',
    type: 'vowel',
    subtype: 'short-vowel',
    name: '短元音 /ʌ/',
    description: '嘴巴半开，舌头放松居中，发音短促有力',
    mouthTip: '嘴巴自然放松张开，舌头不用刻意移动',
    commonMistakes: ['与/ɑː/混淆', '发音太长'],
    difficulty: 2,
    hardForChinese: true,
    confusableWith: ['ɑː', 'ə'],
    minimalPairs: {
      'ɑː': [
        { word1: 'cut', phonetic1: '/kʌt/', word2: 'cart', phonetic2: '/kɑːt/' },
        { word1: 'hut', phonetic1: '/hʌt/', word2: 'heart', phonetic2: '/hɑːt/' },
        { word1: 'duck', phonetic1: '/dʌk/', word2: 'dark', phonetic2: '/dɑːk/' },
        { word1: 'luck', phonetic1: '/lʌk/', word2: 'lark', phonetic2: '/lɑːk/' },
        { word1: 'bud', phonetic1: '/bʌd/', word2: 'bard', phonetic2: '/bɑːd/' },
        { word1: 'cup', phonetic1: '/kʌp/', word2: 'carp', phonetic2: '/kɑːp/' },
        { word1: 'muck', phonetic1: '/mʌk/', word2: 'mark', phonetic2: '/mɑːk/' },
        { word1: 'gust', phonetic1: '/ɡʌst/', word2: 'ghast', phonetic2: '/ɡɑːst/' },
        { word1: 'puck', phonetic1: '/pʌk/', word2: 'park', phonetic2: '/pɑːk/' },
        { word1: 'stuff', phonetic1: '/stʌf/', word2: 'staff', phonetic2: '/stɑːf/' },
      ],
    },
    words: [
      { word: 'cup', phonetic: '/kʌp/', position: 'middle' },
      { word: 'but', phonetic: '/bʌt/', position: 'middle' },
      { word: 'love', phonetic: '/lʌv/', position: 'middle' },
      { word: 'sun', phonetic: '/sʌn/', position: 'middle' },
      { word: 'under', phonetic: '/ˈʌndər/', position: 'beginning' },
    ],
  },
  {
    symbol: 'ɒ',
    type: 'vowel',
    subtype: 'short-vowel',
    name: '短元音 /ɒ/',
    description: '嘴巴圆形张开，舌头后缩低放',
    mouthTip: '嘴巴成圆形，像说"哦"但更短促',
    commonMistakes: ['与/ɔː/混淆', '嘴型不够圆'],
    difficulty: 2,
    hardForChinese: false,
    confusableWith: ['ɔː'],
    minimalPairs: {
      'ɔː': [
        { word1: 'cot', phonetic1: '/kɒt/', word2: 'caught', phonetic2: '/kɔːt/' },
        { word1: 'pot', phonetic1: '/pɒt/', word2: 'port', phonetic2: '/pɔːt/' },
        { word1: 'fox', phonetic1: '/fɒks/', word2: 'forks', phonetic2: '/fɔːks/' },
        { word1: 'stock', phonetic1: '/stɒk/', word2: 'stork', phonetic2: '/stɔːk/' },
        { word1: 'not', phonetic1: '/nɒt/', word2: 'nought', phonetic2: '/nɔːt/' },
        { word1: 'don', phonetic1: '/dɒn/', word2: 'dawn', phonetic2: '/dɔːn/' },
        { word1: 'hot', phonetic1: '/hɒt/', word2: 'halt', phonetic2: '/hɔːlt/' },
        { word1: 'cod', phonetic1: '/kɒd/', word2: 'cord', phonetic2: '/kɔːd/' },
      ],
    },
    words: [
      { word: 'hot', phonetic: '/hɒt/', position: 'middle' },
      { word: 'dog', phonetic: '/dɒɡ/', position: 'middle' },
      { word: 'stop', phonetic: '/stɒp/', position: 'middle' },
      { word: 'box', phonetic: '/bɒks/', position: 'middle' },
      { word: 'clock', phonetic: '/klɒk/', position: 'middle' },
    ],
  },
  {
    symbol: 'ʊ',
    type: 'vowel',
    subtype: 'short-vowel',
    name: '短元音 /ʊ/',
    description: '嘴唇圆起但不紧，舌头后缩，发音短促',
    mouthTip: '嘴唇轻轻圆起，不要太用力',
    commonMistakes: ['与/uː/混淆', '嘴唇太紧'],
    difficulty: 3,
    hardForChinese: true,
    confusableWith: ['uː'],
    minimalPairs: {
      'uː': [
        { word1: 'pull', phonetic1: '/pʊl/', word2: 'pool', phonetic2: '/puːl/' },
        { word1: 'full', phonetic1: '/fʊl/', word2: 'fool', phonetic2: '/fuːl/' },
        { word1: 'look', phonetic1: '/lʊk/', word2: 'Luke', phonetic2: '/luːk/' },
        { word1: 'could', phonetic1: '/kʊd/', word2: 'cooed', phonetic2: '/kuːd/' },
        { word1: 'wood', phonetic1: '/wʊd/', word2: 'wooed', phonetic2: '/wuːd/' },
        { word1: 'foot', phonetic1: '/fʊt/', word2: 'food', phonetic2: '/fuːd/' },
        { word1: 'soot', phonetic1: '/sʊt/', word2: 'suit', phonetic2: '/suːt/' },
        { word1: 'should', phonetic1: '/ʃʊd/', word2: 'shoed', phonetic2: '/ʃuːd/' },
        { word1: 'hood', phonetic1: '/hʊd/', word2: 'who\'d', phonetic2: '/huːd/' },
        { word1: 'stood', phonetic1: '/stʊd/', word2: 'stewed', phonetic2: '/stjuːd/' },
      ],
    },
    words: [
      { word: 'book', phonetic: '/bʊk/', position: 'middle' },
      { word: 'good', phonetic: '/ɡʊd/', position: 'middle' },
      { word: 'put', phonetic: '/pʊt/', position: 'middle' },
      { word: 'look', phonetic: '/lʊk/', position: 'middle' },
      { word: 'could', phonetic: '/kʊd/', position: 'middle' },
    ],
  },
  {
    symbol: 'ə',
    type: 'vowel',
    subtype: 'short-vowel',
    name: '中央元音 /ə/',
    description: '最常见的元音，嘴巴自然放松，发音轻而短',
    mouthTip: '完全放松嘴巴，发一个模糊的"呃"音',
    commonMistakes: ['发音太清晰', '用力过度'],
    difficulty: 2,
    hardForChinese: true,
    confusableWith: ['ɜː', 'ʌ'],
    minimalPairs: {
      'ɜː': [
        { word1: 'about', phonetic1: '/əˈbaʊt/', word2: 'bird', phonetic2: '/bɜːd/' },
        { word1: 'ago', phonetic1: '/əˈɡəʊ/', word2: 'fur', phonetic2: '/fɜː/' },
        { word1: 'apart', phonetic1: '/əˈpɑːt/', word2: 'assert', phonetic2: '/əˈsɜːt/' },
        { word1: 'accept', phonetic1: '/əkˈsept/', word2: 'excerpt', phonetic2: '/ˈeksɜːpt/' },
        { word1: 'above', phonetic1: '/əˈbʌv/', word2: 'herb', phonetic2: '/hɜːb/' },
      ],
    },
    words: [
      { word: 'about', phonetic: '/əˈbaʊt/', position: 'beginning' },
      { word: 'banana', phonetic: '/bəˈnɑːnə/', position: 'middle' },
      { word: 'sofa', phonetic: '/ˈsəʊfə/', position: 'end' },
      { word: 'again', phonetic: '/əˈɡen/', position: 'beginning' },
      { word: 'problem', phonetic: '/ˈprɒbləm/', position: 'middle' },
    ],
  },
];

const longVowels: Phoneme[] = [
  {
    symbol: 'iː',
    type: 'vowel',
    subtype: 'long-vowel',
    name: '长元音 /iː/',
    description: '嘴唇扁平拉开，舌头前伸高抬，发音延长',
    mouthTip: '嘴角向两边拉，露出牙齿，像微笑',
    commonMistakes: ['发音太短', '与/ɪ/混淆'],
    difficulty: 1,
    hardForChinese: false,
    confusableWith: ['ɪ'],
    minimalPairs: {
      'ɪ': [
        { word1: 'seat', phonetic1: '/siːt/', word2: 'sit', phonetic2: '/sɪt/' },
        { word1: 'sheep', phonetic1: '/ʃiːp/', word2: 'ship', phonetic2: '/ʃɪp/' },
        { word1: 'beat', phonetic1: '/biːt/', word2: 'bit', phonetic2: '/bɪt/' },
        { word1: 'feel', phonetic1: '/fiːl/', word2: 'fill', phonetic2: '/fɪl/' },
        { word1: 'heat', phonetic1: '/hiːt/', word2: 'hit', phonetic2: '/hɪt/' },
        { word1: 'leap', phonetic1: '/liːp/', word2: 'lip', phonetic2: '/lɪp/' },
        { word1: 'green', phonetic1: '/ɡriːn/', word2: 'grin', phonetic2: '/ɡrɪn/' },
        { word1: 'seen', phonetic1: '/siːn/', word2: 'sin', phonetic2: '/sɪn/' },
        { word1: 'teal', phonetic1: '/tiːl/', word2: 'till', phonetic2: '/tɪl/' },
        { word1: 'peel', phonetic1: '/piːl/', word2: 'pill', phonetic2: '/pɪl/' },
      ],
    },
    words: [
      { word: 'see', phonetic: '/siː/', position: 'middle' },
      { word: 'eat', phonetic: '/iːt/', position: 'beginning' },
      { word: 'green', phonetic: '/ɡriːn/', position: 'middle' },
      { word: 'please', phonetic: '/pliːz/', position: 'middle' },
      { word: 'easy', phonetic: '/ˈiːzi/', position: 'beginning' },
    ],
  },
  {
    symbol: 'ɑː',
    type: 'vowel',
    subtype: 'long-vowel',
    name: '长元音 /ɑː/',
    description: '嘴巴张大，舌头平放后缩，发音延长',
    mouthTip: '嘴巴尽量张大，像医生检查喉咙时说"啊"',
    commonMistakes: ['嘴巴张得不够大', '发音太短'],
    difficulty: 1,
    hardForChinese: false,
    confusableWith: ['ʌ'],
    minimalPairs: {
      'ʌ': [
        { word1: 'cart', phonetic1: '/kɑːt/', word2: 'cut', phonetic2: '/kʌt/' },
        { word1: 'heart', phonetic1: '/hɑːt/', word2: 'hut', phonetic2: '/hʌt/' },
        { word1: 'dark', phonetic1: '/dɑːk/', word2: 'duck', phonetic2: '/dʌk/' },
        { word1: 'lark', phonetic1: '/lɑːk/', word2: 'luck', phonetic2: '/lʌk/' },
        { word1: 'bard', phonetic1: '/bɑːd/', word2: 'bud', phonetic2: '/bʌd/' },
        { word1: 'carp', phonetic1: '/kɑːp/', word2: 'cup', phonetic2: '/kʌp/' },
        { word1: 'mark', phonetic1: '/mɑːk/', word2: 'muck', phonetic2: '/mʌk/' },
        { word1: 'park', phonetic1: '/pɑːk/', word2: 'puck', phonetic2: '/pʌk/' },
        { word1: 'staff', phonetic1: '/stɑːf/', word2: 'stuff', phonetic2: '/stʌf/' },
        { word1: 'barn', phonetic1: '/bɑːn/', word2: 'bun', phonetic2: '/bʌn/' },
      ],
    },
    words: [
      { word: 'car', phonetic: '/kɑːr/', position: 'middle' },
      { word: 'father', phonetic: '/ˈfɑːðər/', position: 'middle' },
      { word: 'heart', phonetic: '/hɑːrt/', position: 'middle' },
      { word: 'star', phonetic: '/stɑːr/', position: 'middle' },
      { word: 'park', phonetic: '/pɑːrk/', position: 'middle' },
    ],
  },
  {
    symbol: 'ɔː',
    type: 'vowel',
    subtype: 'long-vowel',
    name: '长元音 /ɔː/',
    description: '嘴唇圆起前突，舌头后缩，发音延长',
    mouthTip: '嘴唇成圆形向前突出，像吹口哨的准备动作',
    commonMistakes: ['嘴型不够圆', '与/ɒ/混淆'],
    difficulty: 2,
    hardForChinese: false,
    confusableWith: ['ɒ'],
    minimalPairs: {
      'ɒ': [
        { word1: 'caught', phonetic1: '/kɔːt/', word2: 'cot', phonetic2: '/kɒt/' },
        { word1: 'port', phonetic1: '/pɔːt/', word2: 'pot', phonetic2: '/pɒt/' },
        { word1: 'forks', phonetic1: '/fɔːks/', word2: 'fox', phonetic2: '/fɒks/' },
        { word1: 'stork', phonetic1: '/stɔːk/', word2: 'stock', phonetic2: '/stɒk/' },
        { word1: 'nought', phonetic1: '/nɔːt/', word2: 'not', phonetic2: '/nɒt/' },
        { word1: 'dawn', phonetic1: '/dɔːn/', word2: 'don', phonetic2: '/dɒn/' },
        { word1: 'cord', phonetic1: '/kɔːd/', word2: 'cod', phonetic2: '/kɒd/' },
        { word1: 'halt', phonetic1: '/hɔːlt/', word2: 'hot', phonetic2: '/hɒt/' },
      ],
    },
    words: [
      { word: 'door', phonetic: '/dɔːr/', position: 'middle' },
      { word: 'four', phonetic: '/fɔːr/', position: 'middle' },
      { word: 'more', phonetic: '/mɔːr/', position: 'middle' },
      { word: 'all', phonetic: '/ɔːl/', position: 'beginning' },
      { word: 'water', phonetic: '/ˈwɔːtər/', position: 'middle' },
    ],
  },
  {
    symbol: 'uː',
    type: 'vowel',
    subtype: 'long-vowel',
    name: '长元音 /uː/',
    description: '嘴唇紧圆前突，舌头后缩高抬，发音延长',
    mouthTip: '嘴唇收紧成小圆形向前突出',
    commonMistakes: ['与/ʊ/混淆', '嘴唇不够圆'],
    difficulty: 1,
    hardForChinese: false,
    confusableWith: ['ʊ'],
    minimalPairs: {
      'ʊ': [
        { word1: 'pool', phonetic1: '/puːl/', word2: 'pull', phonetic2: '/pʊl/' },
        { word1: 'fool', phonetic1: '/fuːl/', word2: 'full', phonetic2: '/fʊl/' },
        { word1: 'Luke', phonetic1: '/luːk/', word2: 'look', phonetic2: '/lʊk/' },
        { word1: 'cooed', phonetic1: '/kuːd/', word2: 'could', phonetic2: '/kʊd/' },
        { word1: 'wooed', phonetic1: '/wuːd/', word2: 'wood', phonetic2: '/wʊd/' },
        { word1: 'food', phonetic1: '/fuːd/', word2: 'foot', phonetic2: '/fʊt/' },
        { word1: 'suit', phonetic1: '/suːt/', word2: 'soot', phonetic2: '/sʊt/' },
        { word1: 'shoed', phonetic1: '/ʃuːd/', word2: 'should', phonetic2: '/ʃʊd/' },
        { word1: 'who\'d', phonetic1: '/huːd/', word2: 'hood', phonetic2: '/hʊd/' },
        { word1: 'stewed', phonetic1: '/stjuːd/', word2: 'stood', phonetic2: '/stʊd/' },
      ],
    },
    words: [
      { word: 'food', phonetic: '/fuːd/', position: 'middle' },
      { word: 'blue', phonetic: '/bluː/', position: 'middle' },
      { word: 'school', phonetic: '/skuːl/', position: 'middle' },
      { word: 'moon', phonetic: '/muːn/', position: 'middle' },
      { word: 'true', phonetic: '/truː/', position: 'middle' },
    ],
  },
  {
    symbol: 'ɜː',
    type: 'vowel',
    subtype: 'long-vowel',
    name: '长元音 /ɜː/',
    description: '嘴巴半开，舌头居中微卷，发音延长',
    mouthTip: '嘴巴自然放松，舌头中间略微隆起',
    commonMistakes: ['发音太短', '与/ə/混淆'],
    difficulty: 3,
    hardForChinese: true,
    confusableWith: ['ə'],
    words: [
      { word: 'bird', phonetic: '/bɜːrd/', position: 'middle' },
      { word: 'word', phonetic: '/wɜːrd/', position: 'middle' },
      { word: 'learn', phonetic: '/lɜːrn/', position: 'middle' },
      { word: 'first', phonetic: '/fɜːrst/', position: 'middle' },
      { word: 'early', phonetic: '/ˈɜːrli/', position: 'beginning' },
    ],
  },
];

const diphthongs: Phoneme[] = [
  {
    symbol: 'eɪ',
    type: 'vowel',
    subtype: 'diphthong',
    name: '双元音 /eɪ/',
    description: '从/e/滑向/ɪ/，嘴型由半开变窄',
    mouthTip: '开始时嘴巴半开，然后向/ɪ/的位置收紧',
    commonMistakes: ['滑动不明显', '只发一个音'],
    difficulty: 2,
    hardForChinese: false,
    confusableWith: ['aɪ'],
    minimalPairs: {
      'aɪ': [
        { word1: 'late', phonetic1: '/leɪt/', word2: 'light', phonetic2: '/laɪt/' },
        { word1: 'fail', phonetic1: '/feɪl/', word2: 'file', phonetic2: '/faɪl/' },
        { word1: 'tale', phonetic1: '/teɪl/', word2: 'tile', phonetic2: '/taɪl/' },
        { word1: 'main', phonetic1: '/meɪn/', word2: 'mine', phonetic2: '/maɪn/' },
        { word1: 'wait', phonetic1: '/weɪt/', word2: 'white', phonetic2: '/waɪt/' },
        { word1: 'fate', phonetic1: '/feɪt/', word2: 'fight', phonetic2: '/faɪt/' },
        { word1: 'date', phonetic1: '/deɪt/', word2: 'diet', phonetic2: '/daɪət/' },
        { word1: 'rain', phonetic1: '/reɪn/', word2: 'rhyme', phonetic2: '/raɪm/' },
      ],
    },
    words: [
      { word: 'day', phonetic: '/deɪ/', position: 'middle' },
      { word: 'make', phonetic: '/meɪk/', position: 'middle' },
      { word: 'say', phonetic: '/seɪ/', position: 'middle' },
      { word: 'face', phonetic: '/feɪs/', position: 'middle' },
      { word: 'away', phonetic: '/əˈweɪ/', position: 'end' },
    ],
  },
  {
    symbol: 'aɪ',
    type: 'vowel',
    subtype: 'diphthong',
    name: '双元音 /aɪ/',
    description: '从/a/滑向/ɪ/，嘴型由大变小',
    mouthTip: '开始嘴巴大张，然后向上收紧到/ɪ/',
    commonMistakes: ['开始音不够开', '滑动不够明显'],
    difficulty: 2,
    hardForChinese: false,
    confusableWith: ['eɪ'],
    minimalPairs: {
      'eɪ': [
        { word1: 'light', phonetic1: '/laɪt/', word2: 'late', phonetic2: '/leɪt/' },
        { word1: 'file', phonetic1: '/faɪl/', word2: 'fail', phonetic2: '/feɪl/' },
        { word1: 'tile', phonetic1: '/taɪl/', word2: 'tale', phonetic2: '/teɪl/' },
        { word1: 'mine', phonetic1: '/maɪn/', word2: 'main', phonetic2: '/meɪn/' },
        { word1: 'white', phonetic1: '/waɪt/', word2: 'wait', phonetic2: '/weɪt/' },
        { word1: 'fight', phonetic1: '/faɪt/', word2: 'fate', phonetic2: '/feɪt/' },
        { word1: 'ride', phonetic1: '/raɪd/', word2: 'raid', phonetic2: '/reɪd/' },
        { word1: 'vice', phonetic1: '/vaɪs/', word2: 'vase', phonetic2: '/veɪz/' },
      ],
    },
    words: [
      { word: 'time', phonetic: '/taɪm/', position: 'middle' },
      { word: 'like', phonetic: '/laɪk/', position: 'middle' },
      { word: 'my', phonetic: '/maɪ/', position: 'middle' },
      { word: 'high', phonetic: '/haɪ/', position: 'middle' },
      { word: 'write', phonetic: '/raɪt/', position: 'middle' },
    ],
  },
  {
    symbol: 'ɔɪ',
    type: 'vowel',
    subtype: 'diphthong',
    name: '双元音 /ɔɪ/',
    description: '从/ɔ/滑向/ɪ/，嘴型由圆变扁',
    mouthTip: '开始嘴唇圆起，然后滑向扁平',
    commonMistakes: ['开始音嘴型不圆', '滑动不流畅'],
    difficulty: 2,
    hardForChinese: false,
    confusableWith: ['aɪ'],
    words: [
      { word: 'boy', phonetic: '/bɔɪ/', position: 'middle' },
      { word: 'voice', phonetic: '/vɔɪs/', position: 'middle' },
      { word: 'enjoy', phonetic: '/ɪnˈdʒɔɪ/', position: 'end' },
      { word: 'choice', phonetic: '/tʃɔɪs/', position: 'middle' },
      { word: 'point', phonetic: '/pɔɪnt/', position: 'middle' },
    ],
  },
  {
    symbol: 'əʊ',
    type: 'vowel',
    subtype: 'diphthong',
    name: '双元音 /əʊ/',
    description: '从/ə/滑向/ʊ/，嘴型逐渐收圆',
    mouthTip: '开始嘴巴放松，然后慢慢收圆',
    commonMistakes: ['起始音太清晰', '结尾不够圆'],
    difficulty: 3,
    hardForChinese: true,
    confusableWith: ['aʊ'],
    minimalPairs: {
      'aʊ': [
        { word1: 'tone', phonetic1: '/təʊn/', word2: 'town', phonetic2: '/taʊn/' },
        { word1: 'goat', phonetic1: '/ɡəʊt/', word2: 'gout', phonetic2: '/ɡaʊt/' },
        { word1: 'load', phonetic1: '/ləʊd/', word2: 'loud', phonetic2: '/laʊd/' },
        { word1: 'coal', phonetic1: '/kəʊl/', word2: 'cowl', phonetic2: '/kaʊl/' },
        { word1: 'boat', phonetic1: '/bəʊt/', word2: 'bout', phonetic2: '/baʊt/' },
        { word1: 'nose', phonetic1: '/nəʊz/', word2: 'nous', phonetic2: '/naʊs/' },
        { word1: 'phone', phonetic1: '/fəʊn/', word2: 'frown', phonetic2: '/fraʊn/' },
        { word1: 'groan', phonetic1: '/ɡrəʊn/', word2: 'grown', phonetic2: '/ɡraʊn/' },
      ],
    },
    words: [
      { word: 'go', phonetic: '/ɡəʊ/', position: 'middle' },
      { word: 'home', phonetic: '/həʊm/', position: 'middle' },
      { word: 'show', phonetic: '/ʃəʊ/', position: 'middle' },
      { word: 'phone', phonetic: '/fəʊn/', position: 'middle' },
      { word: 'know', phonetic: '/nəʊ/', position: 'middle' },
    ],
  },
  {
    symbol: 'aʊ',
    type: 'vowel',
    subtype: 'diphthong',
    name: '双元音 /aʊ/',
    description: '从/a/滑向/ʊ/，嘴型由大张变收圆',
    mouthTip: '开始嘴巴大张，然后收成圆形',
    commonMistakes: ['开始音不够开', '结尾不够圆'],
    difficulty: 2,
    hardForChinese: false,
    confusableWith: ['əʊ'],
    minimalPairs: {
      'əʊ': [
        { word1: 'town', phonetic1: '/taʊn/', word2: 'tone', phonetic2: '/təʊn/' },
        { word1: 'gout', phonetic1: '/ɡaʊt/', word2: 'goat', phonetic2: '/ɡəʊt/' },
        { word1: 'loud', phonetic1: '/laʊd/', word2: 'load', phonetic2: '/ləʊd/' },
        { word1: 'cowl', phonetic1: '/kaʊl/', word2: 'coal', phonetic2: '/kəʊl/' },
        { word1: 'bout', phonetic1: '/baʊt/', word2: 'boat', phonetic2: '/bəʊt/' },
        { word1: 'noun', phonetic1: '/naʊn/', word2: 'known', phonetic2: '/nəʊn/' },
        { word1: 'frown', phonetic1: '/fraʊn/', word2: 'phone', phonetic2: '/fəʊn/' },
        { word1: 'ground', phonetic1: '/ɡraʊnd/', word2: 'groan', phonetic2: '/ɡrəʊn/' },
      ],
    },
    words: [
      { word: 'now', phonetic: '/naʊ/', position: 'middle' },
      { word: 'house', phonetic: '/haʊs/', position: 'middle' },
      { word: 'out', phonetic: '/aʊt/', position: 'beginning' },
      { word: 'about', phonetic: '/əˈbaʊt/', position: 'middle' },
      { word: 'down', phonetic: '/daʊn/', position: 'middle' },
    ],
  },
  {
    symbol: 'ɪə',
    type: 'vowel',
    subtype: 'diphthong',
    name: '双元音 /ɪə/',
    description: '从/ɪ/滑向/ə/，嘴型由窄变放松',
    mouthTip: '开始嘴角拉开，然后放松',
    commonMistakes: ['两个音分得太开', '滑动不自然'],
    difficulty: 3,
    hardForChinese: true,
    confusableWith: ['eə'],
    minimalPairs: {
      'eə': [
        { word1: 'here', phonetic1: '/hɪər/', word2: 'hair', phonetic2: '/heər/' },
        { word1: 'beer', phonetic1: '/bɪər/', word2: 'bear', phonetic2: '/beər/' },
        { word1: 'dear', phonetic1: '/dɪər/', word2: 'dare', phonetic2: '/deər/' },
        { word1: 'peer', phonetic1: '/pɪər/', word2: 'pair', phonetic2: '/peər/' },
        { word1: 'sheer', phonetic1: '/ʃɪər/', word2: 'share', phonetic2: '/ʃeər/' },
        { word1: 'fear', phonetic1: '/fɪər/', word2: 'fair', phonetic2: '/feər/' },
        { word1: 'steer', phonetic1: '/stɪər/', word2: 'stare', phonetic2: '/steər/' },
        { word1: 'tear', phonetic1: '/tɪər/', word2: 'tear', phonetic2: '/teər/' },
      ],
    },
    words: [
      { word: 'here', phonetic: '/hɪər/', position: 'middle' },
      { word: 'near', phonetic: '/nɪər/', position: 'middle' },
      { word: 'idea', phonetic: '/aɪˈdɪə/', position: 'end' },
      { word: 'clear', phonetic: '/klɪər/', position: 'middle' },
      { word: 'year', phonetic: '/jɪər/', position: 'middle' },
    ],
  },
  {
    symbol: 'eə',
    type: 'vowel',
    subtype: 'diphthong',
    name: '双元音 /eə/',
    description: '从/e/滑向/ə/，嘴型由半开变放松',
    mouthTip: '开始嘴巴半开，然后放松',
    commonMistakes: ['与/ɪə/混淆', '滑动不明显'],
    difficulty: 3,
    hardForChinese: true,
    confusableWith: ['ɪə'],
    minimalPairs: {
      'ɪə': [
        { word1: 'hair', phonetic1: '/heər/', word2: 'here', phonetic2: '/hɪər/' },
        { word1: 'bear', phonetic1: '/beər/', word2: 'beer', phonetic2: '/bɪər/' },
        { word1: 'dare', phonetic1: '/deər/', word2: 'dear', phonetic2: '/dɪər/' },
        { word1: 'pair', phonetic1: '/peər/', word2: 'peer', phonetic2: '/pɪər/' },
        { word1: 'share', phonetic1: '/ʃeər/', word2: 'sheer', phonetic2: '/ʃɪər/' },
        { word1: 'fair', phonetic1: '/feər/', word2: 'fear', phonetic2: '/fɪər/' },
        { word1: 'stare', phonetic1: '/steər/', word2: 'steer', phonetic2: '/stɪər/' },
        { word1: 'wear', phonetic1: '/weər/', word2: 'we\'re', phonetic2: '/wɪər/' },
      ],
    },
    words: [
      { word: 'where', phonetic: '/weər/', position: 'middle' },
      { word: 'care', phonetic: '/keər/', position: 'middle' },
      { word: 'there', phonetic: '/ðeər/', position: 'middle' },
      { word: 'fair', phonetic: '/feər/', position: 'middle' },
      { word: 'hair', phonetic: '/heər/', position: 'middle' },
    ],
  },
  {
    symbol: 'ʊə',
    type: 'vowel',
    subtype: 'diphthong',
    name: '双元音 /ʊə/',
    description: '从/ʊ/滑向/ə/，嘴型由圆变放松',
    mouthTip: '开始嘴唇微圆，然后放松',
    commonMistakes: ['开始音不够圆', '滑动不流畅'],
    difficulty: 3,
    hardForChinese: true,
    confusableWith: ['ɔː'],
    words: [
      { word: 'tour', phonetic: '/tʊər/', position: 'middle' },
      { word: 'pure', phonetic: '/pjʊər/', position: 'middle' },
      { word: 'sure', phonetic: '/ʃʊər/', position: 'middle' },
      { word: 'poor', phonetic: '/pʊər/', position: 'middle' },
      { word: 'cure', phonetic: '/kjʊər/', position: 'middle' },
    ],
  },
];

// ============================================================================
// 辅音 (Consonants) - 24个
// ============================================================================

const plosives: Phoneme[] = [
  {
    symbol: 'p',
    type: 'consonant',
    subtype: 'voiceless',
    name: '爆破音 /p/',
    description: '双唇紧闭，气流冲出，声带不振动',
    mouthTip: '双唇紧闭后突然打开，送出一股气流',
    commonMistakes: ['送气不足', '与/b/混淆'],
    difficulty: 1,
    hardForChinese: false,
    confusableWith: ['b'],
    minimalPairs: {
      'b': [
        { word1: 'pin', phonetic1: '/pɪn/', word2: 'bin', phonetic2: '/bɪn/' },
        { word1: 'pat', phonetic1: '/pæt/', word2: 'bat', phonetic2: '/bæt/' },
        { word1: 'pet', phonetic1: '/pet/', word2: 'bet', phonetic2: '/bet/' },
        { word1: 'cap', phonetic1: '/kæp/', word2: 'cab', phonetic2: '/kæb/' },
        { word1: 'pie', phonetic1: '/paɪ/', word2: 'buy', phonetic2: '/baɪ/' },
        { word1: 'pack', phonetic1: '/pæk/', word2: 'back', phonetic2: '/bæk/' },
        { word1: 'pear', phonetic1: '/peər/', word2: 'bear', phonetic2: '/beər/' },
        { word1: 'pull', phonetic1: '/pʊl/', word2: 'bull', phonetic2: '/bʊl/' },
      ],
    },
    words: [
      { word: 'pen', phonetic: '/pen/', position: 'beginning' },
      { word: 'apple', phonetic: '/ˈæpl/', position: 'middle' },
      { word: 'stop', phonetic: '/stɒp/', position: 'end' },
      { word: 'happy', phonetic: '/ˈhæpi/', position: 'middle' },
      { word: 'people', phonetic: '/ˈpiːpl/', position: 'beginning' },
    ],
  },
  {
    symbol: 'b',
    type: 'consonant',
    subtype: 'voiced',
    name: '爆破音 /b/',
    description: '双唇紧闭，气流冲出，声带振动',
    mouthTip: '双唇紧闭后打开，同时声带振动',
    commonMistakes: ['声带振动不够', '与/p/混淆'],
    difficulty: 1,
    hardForChinese: false,
    confusableWith: ['p'],
    minimalPairs: {
      'p': [
        { word1: 'bin', phonetic1: '/bɪn/', word2: 'pin', phonetic2: '/pɪn/' },
        { word1: 'bat', phonetic1: '/bæt/', word2: 'pat', phonetic2: '/pæt/' },
        { word1: 'bet', phonetic1: '/bet/', word2: 'pet', phonetic2: '/pet/' },
        { word1: 'cab', phonetic1: '/kæb/', word2: 'cap', phonetic2: '/kæp/' },
        { word1: 'buy', phonetic1: '/baɪ/', word2: 'pie', phonetic2: '/paɪ/' },
        { word1: 'back', phonetic1: '/bæk/', word2: 'pack', phonetic2: '/pæk/' },
        { word1: 'bear', phonetic1: '/beər/', word2: 'pear', phonetic2: '/peər/' },
        { word1: 'bull', phonetic1: '/bʊl/', word2: 'pull', phonetic2: '/pʊl/' },
      ],
    },
    words: [
      { word: 'book', phonetic: '/bʊk/', position: 'beginning' },
      { word: 'baby', phonetic: '/ˈbeɪbi/', position: 'beginning' },
      { word: 'job', phonetic: '/dʒɒb/', position: 'end' },
      { word: 'table', phonetic: '/ˈteɪbl/', position: 'middle' },
      { word: 'about', phonetic: '/əˈbaʊt/', position: 'middle' },
    ],
  },
  {
    symbol: 't',
    type: 'consonant',
    subtype: 'voiceless',
    name: '爆破音 /t/',
    description: '舌尖抵上齿龈，气流冲出，声带不振动',
    mouthTip: '舌尖抵住上牙龈后突然放开',
    commonMistakes: ['送气不足', '与/d/混淆'],
    difficulty: 1,
    hardForChinese: false,
    confusableWith: ['d'],
    minimalPairs: {
      'd': [
        { word1: 'tie', phonetic1: '/taɪ/', word2: 'die', phonetic2: '/daɪ/' },
        { word1: 'ten', phonetic1: '/ten/', word2: 'den', phonetic2: '/den/' },
        { word1: 'bat', phonetic1: '/bæt/', word2: 'bad', phonetic2: '/bæd/' },
        { word1: 'set', phonetic1: '/set/', word2: 'said', phonetic2: '/sed/' },
        { word1: 'time', phonetic1: '/taɪm/', word2: 'dime', phonetic2: '/daɪm/' },
        { word1: 'tip', phonetic1: '/tɪp/', word2: 'dip', phonetic2: '/dɪp/' },
        { word1: 'town', phonetic1: '/taʊn/', word2: 'down', phonetic2: '/daʊn/' },
        { word1: 'train', phonetic1: '/treɪn/', word2: 'drain', phonetic2: '/dreɪn/' },
      ],
    },
    words: [
      { word: 'time', phonetic: '/taɪm/', position: 'beginning' },
      { word: 'water', phonetic: '/ˈwɔːtər/', position: 'middle' },
      { word: 'cat', phonetic: '/kæt/', position: 'end' },
      { word: 'better', phonetic: '/ˈbetər/', position: 'middle' },
      { word: 'that', phonetic: '/ðæt/', position: 'end' },
    ],
  },
  {
    symbol: 'd',
    type: 'consonant',
    subtype: 'voiced',
    name: '爆破音 /d/',
    description: '舌尖抵上齿龈，气流冲出，声带振动',
    mouthTip: '舌尖抵住上牙龈后放开，同时声带振动',
    commonMistakes: ['声带振动不够', '与/t/混淆'],
    difficulty: 1,
    hardForChinese: false,
    confusableWith: ['t'],
    minimalPairs: {
      't': [
        { word1: 'die', phonetic1: '/daɪ/', word2: 'tie', phonetic2: '/taɪ/' },
        { word1: 'den', phonetic1: '/den/', word2: 'ten', phonetic2: '/ten/' },
        { word1: 'bad', phonetic1: '/bæd/', word2: 'bat', phonetic2: '/bæt/' },
        { word1: 'said', phonetic1: '/sed/', word2: 'set', phonetic2: '/set/' },
        { word1: 'dime', phonetic1: '/daɪm/', word2: 'time', phonetic2: '/taɪm/' },
        { word1: 'dip', phonetic1: '/dɪp/', word2: 'tip', phonetic2: '/tɪp/' },
        { word1: 'down', phonetic1: '/daʊn/', word2: 'town', phonetic2: '/taʊn/' },
        { word1: 'drain', phonetic1: '/dreɪn/', word2: 'train', phonetic2: '/treɪn/' },
      ],
    },
    words: [
      { word: 'day', phonetic: '/deɪ/', position: 'beginning' },
      { word: 'body', phonetic: '/ˈbɒdi/', position: 'middle' },
      { word: 'good', phonetic: '/ɡʊd/', position: 'end' },
      { word: 'did', phonetic: '/dɪd/', position: 'beginning' },
      { word: 'building', phonetic: '/ˈbɪldɪŋ/', position: 'middle' },
    ],
  },
  {
    symbol: 'k',
    type: 'consonant',
    subtype: 'voiceless',
    name: '爆破音 /k/',
    description: '舌后部抵软腭，气流冲出，声带不振动',
    mouthTip: '舌根抵住软腭后突然放开',
    commonMistakes: ['送气不足', '与/ɡ/混淆'],
    difficulty: 1,
    hardForChinese: false,
    confusableWith: ['ɡ'],
    minimalPairs: {
      'ɡ': [
        { word1: 'came', phonetic1: '/keɪm/', word2: 'game', phonetic2: '/ɡeɪm/' },
        { word1: 'coat', phonetic1: '/kəʊt/', word2: 'goat', phonetic2: '/ɡəʊt/' },
        { word1: 'curl', phonetic1: '/kɜːl/', word2: 'girl', phonetic2: '/ɡɜːl/' },
        { word1: 'cap', phonetic1: '/kæp/', word2: 'gap', phonetic2: '/ɡæp/' },
        { word1: 'class', phonetic1: '/klɑːs/', word2: 'glass', phonetic2: '/ɡlɑːs/' },
        { word1: 'cold', phonetic1: '/kəʊld/', word2: 'gold', phonetic2: '/ɡəʊld/' },
        { word1: 'crow', phonetic1: '/krəʊ/', word2: 'grow', phonetic2: '/ɡrəʊ/' },
        { word1: 'cave', phonetic1: '/keɪv/', word2: 'gave', phonetic2: '/ɡeɪv/' },
      ],
    },
    words: [
      { word: 'cat', phonetic: '/kæt/', position: 'beginning' },
      { word: 'back', phonetic: '/bæk/', position: 'end' },
      { word: 'quick', phonetic: '/kwɪk/', position: 'beginning' },
      { word: 'make', phonetic: '/meɪk/', position: 'end' },
      { word: 'kitchen', phonetic: '/ˈkɪtʃɪn/', position: 'beginning' },
    ],
  },
  {
    symbol: 'ɡ',
    type: 'consonant',
    subtype: 'voiced',
    name: '爆破音 /ɡ/',
    description: '舌后部抵软腭，气流冲出，声带振动',
    mouthTip: '舌根抵住软腭后放开，同时声带振动',
    commonMistakes: ['声带振动不够', '与/k/混淆'],
    difficulty: 1,
    hardForChinese: false,
    confusableWith: ['k'],
    minimalPairs: {
      'k': [
        { word1: 'game', phonetic1: '/ɡeɪm/', word2: 'came', phonetic2: '/keɪm/' },
        { word1: 'goat', phonetic1: '/ɡəʊt/', word2: 'coat', phonetic2: '/kəʊt/' },
        { word1: 'girl', phonetic1: '/ɡɜːl/', word2: 'curl', phonetic2: '/kɜːl/' },
        { word1: 'gap', phonetic1: '/ɡæp/', word2: 'cap', phonetic2: '/kæp/' },
        { word1: 'glass', phonetic1: '/ɡlɑːs/', word2: 'class', phonetic2: '/klɑːs/' },
        { word1: 'gold', phonetic1: '/ɡəʊld/', word2: 'cold', phonetic2: '/kəʊld/' },
        { word1: 'grow', phonetic1: '/ɡrəʊ/', word2: 'crow', phonetic2: '/krəʊ/' },
        { word1: 'gave', phonetic1: '/ɡeɪv/', word2: 'cave', phonetic2: '/keɪv/' },
      ],
    },
    words: [
      { word: 'go', phonetic: '/ɡəʊ/', position: 'beginning' },
      { word: 'big', phonetic: '/bɪɡ/', position: 'end' },
      { word: 'game', phonetic: '/ɡeɪm/', position: 'beginning' },
      { word: 'again', phonetic: '/əˈɡen/', position: 'middle' },
      { word: 'dog', phonetic: '/dɒɡ/', position: 'end' },
    ],
  },
];

const fricatives: Phoneme[] = [
  {
    symbol: 'f',
    type: 'consonant',
    subtype: 'voiceless',
    name: '摩擦音 /f/',
    description: '上齿轻咬下唇，气流摩擦而出，声带不振动',
    mouthTip: '上牙轻轻接触下唇，吹气',
    commonMistakes: ['咬得太重', '与/v/混淆'],
    difficulty: 1,
    hardForChinese: false,
    confusableWith: ['v'],
    minimalPairs: {
      'v': [
        { word1: 'fan', phonetic1: '/fæn/', word2: 'van', phonetic2: '/væn/' },
        { word1: 'fast', phonetic1: '/fɑːst/', word2: 'vast', phonetic2: '/vɑːst/' },
        { word1: 'few', phonetic1: '/fjuː/', word2: 'view', phonetic2: '/vjuː/' },
        { word1: 'safe', phonetic1: '/seɪf/', word2: 'save', phonetic2: '/seɪv/' },
        { word1: 'leaf', phonetic1: '/liːf/', word2: 'leave', phonetic2: '/liːv/' },
        { word1: 'fine', phonetic1: '/faɪn/', word2: 'vine', phonetic2: '/vaɪn/' },
        { word1: 'feel', phonetic1: '/fiːl/', word2: 'veal', phonetic2: '/viːl/' },
        { word1: 'ferry', phonetic1: '/ˈferi/', word2: 'very', phonetic2: '/ˈveri/' },
      ],
    },
    words: [
      { word: 'food', phonetic: '/fuːd/', position: 'beginning' },
      { word: 'life', phonetic: '/laɪf/', position: 'end' },
      { word: 'coffee', phonetic: '/ˈkɒfi/', position: 'middle' },
      { word: 'after', phonetic: '/ˈɑːftər/', position: 'middle' },
      { word: 'different', phonetic: '/ˈdɪfrənt/', position: 'middle' },
    ],
  },
  {
    symbol: 'v',
    type: 'consonant',
    subtype: 'voiced',
    name: '摩擦音 /v/',
    description: '上齿轻咬下唇，气流摩擦而出，声带振动',
    mouthTip: '上牙轻接触下唇，声带振动',
    commonMistakes: ['与/w/混淆', '声带振动不够'],
    difficulty: 3,
    hardForChinese: true,
    confusableWith: ['w', 'f'],
    minimalPairs: {
      'w': [
        { word1: 'vine', phonetic1: '/vaɪn/', word2: 'wine', phonetic2: '/waɪn/' },
        { word1: 'vest', phonetic1: '/vest/', word2: 'west', phonetic2: '/west/' },
        { word1: 'vet', phonetic1: '/vet/', word2: 'wet', phonetic2: '/wet/' },
        { word1: 'veil', phonetic1: '/veɪl/', word2: 'wail', phonetic2: '/weɪl/' },
        { word1: 'verse', phonetic1: '/vɜːs/', word2: 'worse', phonetic2: '/wɜːs/' },
        { word1: 'vale', phonetic1: '/veɪl/', word2: 'whale', phonetic2: '/weɪl/' },
        { word1: 'vow', phonetic1: '/vaʊ/', word2: 'wow', phonetic2: '/waʊ/' },
        { word1: 'veer', phonetic1: '/vɪər/', word2: 'we\'re', phonetic2: '/wɪər/' },
        { word1: 'vent', phonetic1: '/vent/', word2: 'went', phonetic2: '/went/' },
        { word1: 'vain', phonetic1: '/veɪn/', word2: 'wane', phonetic2: '/weɪn/' },
      ],
      'f': [
        { word1: 'van', phonetic1: '/væn/', word2: 'fan', phonetic2: '/fæn/' },
        { word1: 'vast', phonetic1: '/vɑːst/', word2: 'fast', phonetic2: '/fɑːst/' },
        { word1: 'view', phonetic1: '/vjuː/', word2: 'few', phonetic2: '/fjuː/' },
        { word1: 'save', phonetic1: '/seɪv/', word2: 'safe', phonetic2: '/seɪf/' },
        { word1: 'leave', phonetic1: '/liːv/', word2: 'leaf', phonetic2: '/liːf/' },
        { word1: 'vine', phonetic1: '/vaɪn/', word2: 'fine', phonetic2: '/faɪn/' },
        { word1: 'veal', phonetic1: '/viːl/', word2: 'feel', phonetic2: '/fiːl/' },
        { word1: 'very', phonetic1: '/ˈveri/', word2: 'ferry', phonetic2: '/ˈferi/' },
      ],
    },
    words: [
      { word: 'very', phonetic: '/ˈveri/', position: 'beginning' },
      { word: 'love', phonetic: '/lʌv/', position: 'end' },
      { word: 'have', phonetic: '/hæv/', position: 'end' },
      { word: 'video', phonetic: '/ˈvɪdiəʊ/', position: 'beginning' },
      { word: 'over', phonetic: '/ˈəʊvər/', position: 'middle' },
    ],
  },
  {
    symbol: 'θ',
    type: 'consonant',
    subtype: 'voiceless',
    name: '摩擦音 /θ/',
    description: '舌尖轻抵上齿，气流从齿间摩擦而出，声带不振动',
    mouthTip: '舌尖伸出轻轻接触上齿，吹气',
    commonMistakes: ['发成/s/或/f/', '舌头伸出不够'],
    difficulty: 4,
    hardForChinese: true,
    confusableWith: ['s', 'f'],
    minimalPairs: {
      's': [
        { word1: 'think', phonetic1: '/θɪŋk/', word2: 'sink', phonetic2: '/sɪŋk/' },
        { word1: 'thick', phonetic1: '/θɪk/', word2: 'sick', phonetic2: '/sɪk/' },
        { word1: 'thin', phonetic1: '/θɪn/', word2: 'sin', phonetic2: '/sɪn/' },
        { word1: 'path', phonetic1: '/pɑːθ/', word2: 'pass', phonetic2: '/pɑːs/' },
        { word1: 'math', phonetic1: '/mæθ/', word2: 'mass', phonetic2: '/mæs/' },
        { word1: 'theme', phonetic1: '/θiːm/', word2: 'seem', phonetic2: '/siːm/' },
        { word1: 'thumb', phonetic1: '/θʌm/', word2: 'sum', phonetic2: '/sʌm/' },
        { word1: 'thaw', phonetic1: '/θɔː/', word2: 'saw', phonetic2: '/sɔː/' },
        { word1: 'faith', phonetic1: '/feɪθ/', word2: 'face', phonetic2: '/feɪs/' },
        { word1: 'mouth', phonetic1: '/maʊθ/', word2: 'mouse', phonetic2: '/maʊs/' },
      ],
    },
    words: [
      { word: 'think', phonetic: '/θɪŋk/', position: 'beginning' },
      { word: 'thank', phonetic: '/θæŋk/', position: 'beginning' },
      { word: 'three', phonetic: '/θriː/', position: 'beginning' },
      { word: 'bath', phonetic: '/bɑːθ/', position: 'end' },
      { word: 'birthday', phonetic: '/ˈbɜːθdeɪ/', position: 'middle' },
    ],
  },
  {
    symbol: 'ð',
    type: 'consonant',
    subtype: 'voiced',
    name: '摩擦音 /ð/',
    description: '舌尖轻抵上齿，气流从齿间摩擦而出，声带振动',
    mouthTip: '舌尖伸出接触上齿，声带振动',
    commonMistakes: ['发成/z/或/d/', '声带振动不够'],
    difficulty: 4,
    hardForChinese: true,
    confusableWith: ['z', 'd'],
    minimalPairs: {
      'd': [
        { word1: 'they', phonetic1: '/ðeɪ/', word2: 'day', phonetic2: '/deɪ/' },
        { word1: 'then', phonetic1: '/ðen/', word2: 'den', phonetic2: '/den/' },
        { word1: 'there', phonetic1: '/ðeər/', word2: 'dare', phonetic2: '/deər/' },
        { word1: 'though', phonetic1: '/ðəʊ/', word2: 'dough', phonetic2: '/dəʊ/' },
        { word1: 'worthy', phonetic1: '/ˈwɜːði/', word2: 'wordy', phonetic2: '/ˈwɜːdi/' },
        { word1: 'this', phonetic1: '/ðɪs/', word2: 'diss', phonetic2: '/dɪs/' },
        { word1: 'than', phonetic1: '/ðæn/', word2: 'Dan', phonetic2: '/dæn/' },
        { word1: 'thee', phonetic1: '/ðiː/', word2: 'D', phonetic2: '/diː/' },
        { word1: 'that', phonetic1: '/ðæt/', word2: 'dat', phonetic2: '/dæt/' },
        { word1: 'those', phonetic1: '/ðəʊz/', word2: 'doze', phonetic2: '/dəʊz/' },
      ],
    },
    words: [
      { word: 'this', phonetic: '/ðɪs/', position: 'beginning' },
      { word: 'that', phonetic: '/ðæt/', position: 'beginning' },
      { word: 'the', phonetic: '/ðə/', position: 'beginning' },
      { word: 'mother', phonetic: '/ˈmʌðər/', position: 'middle' },
      { word: 'weather', phonetic: '/ˈweðər/', position: 'middle' },
    ],
  },
  {
    symbol: 's',
    type: 'consonant',
    subtype: 'voiceless',
    name: '摩擦音 /s/',
    description: '舌尖靠近上齿龈，气流从窄缝中摩擦而出，声带不振动',
    mouthTip: '舌尖靠近上牙龈，像蛇发出的"嘶"声',
    commonMistakes: ['与/ʃ/混淆', '气流太弱'],
    difficulty: 1,
    hardForChinese: false,
    confusableWith: ['z', 'ʃ'],
    minimalPairs: {
      'z': [
        { word1: 'sip', phonetic1: '/sɪp/', word2: 'zip', phonetic2: '/zɪp/' },
        { word1: 'seal', phonetic1: '/siːl/', word2: 'zeal', phonetic2: '/ziːl/' },
        { word1: 'rice', phonetic1: '/raɪs/', word2: 'rise', phonetic2: '/raɪz/' },
        { word1: 'bus', phonetic1: '/bʌs/', word2: 'buzz', phonetic2: '/bʌz/' },
        { word1: 'peace', phonetic1: '/piːs/', word2: 'peas', phonetic2: '/piːz/' },
        { word1: 'price', phonetic1: '/praɪs/', word2: 'prize', phonetic2: '/praɪz/' },
        { word1: 'ice', phonetic1: '/aɪs/', word2: 'eyes', phonetic2: '/aɪz/' },
        { word1: 'loose', phonetic1: '/luːs/', word2: 'lose', phonetic2: '/luːz/' },
      ],
      'ʃ': [
        { word1: 'see', phonetic1: '/siː/', word2: 'she', phonetic2: '/ʃiː/' },
        { word1: 'sip', phonetic1: '/sɪp/', word2: 'ship', phonetic2: '/ʃɪp/' },
        { word1: 'save', phonetic1: '/seɪv/', word2: 'shave', phonetic2: '/ʃeɪv/' },
        { word1: 'sell', phonetic1: '/sel/', word2: 'shell', phonetic2: '/ʃel/' },
        { word1: 'sort', phonetic1: '/sɔːt/', word2: 'short', phonetic2: '/ʃɔːt/' },
        { word1: 'sock', phonetic1: '/sɒk/', word2: 'shock', phonetic2: '/ʃɒk/' },
        { word1: 'sign', phonetic1: '/saɪn/', word2: 'shine', phonetic2: '/ʃaɪn/' },
        { word1: 'so', phonetic1: '/səʊ/', word2: 'show', phonetic2: '/ʃəʊ/' },
      ],
    },
    words: [
      { word: 'see', phonetic: '/siː/', position: 'beginning' },
      { word: 'sun', phonetic: '/sʌn/', position: 'beginning' },
      { word: 'yes', phonetic: '/jes/', position: 'end' },
      { word: 'sister', phonetic: '/ˈsɪstər/', position: 'beginning' },
      { word: 'class', phonetic: '/klɑːs/', position: 'end' },
    ],
  },
  {
    symbol: 'z',
    type: 'consonant',
    subtype: 'voiced',
    name: '摩擦音 /z/',
    description: '舌尖靠近上齿龈，气流从窄缝中摩擦而出，声带振动',
    mouthTip: '与/s/相同位置，但声带振动',
    commonMistakes: ['声带振动不够', '与/s/混淆'],
    difficulty: 2,
    hardForChinese: true,
    confusableWith: ['s'],
    minimalPairs: {
      's': [
        { word1: 'zip', phonetic1: '/zɪp/', word2: 'sip', phonetic2: '/sɪp/' },
        { word1: 'zeal', phonetic1: '/ziːl/', word2: 'seal', phonetic2: '/siːl/' },
        { word1: 'rise', phonetic1: '/raɪz/', word2: 'rice', phonetic2: '/raɪs/' },
        { word1: 'buzz', phonetic1: '/bʌz/', word2: 'bus', phonetic2: '/bʌs/' },
        { word1: 'peas', phonetic1: '/piːz/', word2: 'peace', phonetic2: '/piːs/' },
        { word1: 'prize', phonetic1: '/praɪz/', word2: 'price', phonetic2: '/praɪs/' },
        { word1: 'eyes', phonetic1: '/aɪz/', word2: 'ice', phonetic2: '/aɪs/' },
        { word1: 'lose', phonetic1: '/luːz/', word2: 'loose', phonetic2: '/luːs/' },
      ],
    },
    words: [
      { word: 'zoo', phonetic: '/zuː/', position: 'beginning' },
      { word: 'is', phonetic: '/ɪz/', position: 'end' },
      { word: 'rose', phonetic: '/rəʊz/', position: 'end' },
      { word: 'zero', phonetic: '/ˈzɪərəʊ/', position: 'beginning' },
      { word: 'music', phonetic: '/ˈmjuːzɪk/', position: 'middle' },
    ],
  },
  {
    symbol: 'ʃ',
    type: 'consonant',
    subtype: 'voiceless',
    name: '摩擦音 /ʃ/',
    description: '舌面靠近硬腭，嘴唇微圆，气流摩擦而出，声带不振动',
    mouthTip: '嘴唇微微圆起，发出"嘘"的声音',
    commonMistakes: ['嘴唇不够圆', '与/s/混淆'],
    difficulty: 2,
    hardForChinese: false,
    confusableWith: ['ʒ', 's'],
    minimalPairs: {
      's': [
        { word1: 'she', phonetic1: '/ʃiː/', word2: 'see', phonetic2: '/siː/' },
        { word1: 'ship', phonetic1: '/ʃɪp/', word2: 'sip', phonetic2: '/sɪp/' },
        { word1: 'shave', phonetic1: '/ʃeɪv/', word2: 'save', phonetic2: '/seɪv/' },
        { word1: 'shell', phonetic1: '/ʃel/', word2: 'sell', phonetic2: '/sel/' },
        { word1: 'short', phonetic1: '/ʃɔːt/', word2: 'sort', phonetic2: '/sɔːt/' },
        { word1: 'shock', phonetic1: '/ʃɒk/', word2: 'sock', phonetic2: '/sɒk/' },
        { word1: 'shine', phonetic1: '/ʃaɪn/', word2: 'sign', phonetic2: '/saɪn/' },
        { word1: 'show', phonetic1: '/ʃəʊ/', word2: 'so', phonetic2: '/səʊ/' },
      ],
    },
    words: [
      { word: 'she', phonetic: '/ʃiː/', position: 'beginning' },
      { word: 'fish', phonetic: '/fɪʃ/', position: 'end' },
      { word: 'ship', phonetic: '/ʃɪp/', position: 'beginning' },
      { word: 'English', phonetic: '/ˈɪŋɡlɪʃ/', position: 'end' },
      { word: 'nation', phonetic: '/ˈneɪʃn/', position: 'middle' },
    ],
  },
  {
    symbol: 'ʒ',
    type: 'consonant',
    subtype: 'voiced',
    name: '摩擦音 /ʒ/',
    description: '舌面靠近硬腭，嘴唇微圆，气流摩擦而出，声带振动',
    mouthTip: '与/ʃ/相同位置，但声带振动',
    commonMistakes: ['与/ʃ/混淆', '发成/dʒ/'],
    difficulty: 3,
    hardForChinese: true,
    confusableWith: ['ʃ', 'dʒ'],
    minimalPairs: {
      'ʃ': [
        { word1: 'measure', phonetic1: '/ˈmeʒər/', word2: 'mesher', phonetic2: '/ˈmeʃər/' },
        { word1: 'vision', phonetic1: '/ˈvɪʒn/', word2: 'fission', phonetic2: '/ˈfɪʃn/' },
        { word1: 'leisure', phonetic1: '/ˈleʒər/', word2: 'lecher', phonetic2: '/ˈletʃər/' },
        { word1: 'confusion', phonetic1: '/kənˈfjuːʒn/', word2: 'Confucian', phonetic2: '/kənˈfjuːʃn/' },
        { word1: 'garage', phonetic1: '/ˈɡærɑːʒ/', word2: 'galosh', phonetic2: '/ɡəˈlɒʃ/' },
      ],
    },
    words: [
      { word: 'pleasure', phonetic: '/ˈpleʒər/', position: 'middle' },
      { word: 'measure', phonetic: '/ˈmeʒər/', position: 'middle' },
      { word: 'vision', phonetic: '/ˈvɪʒn/', position: 'middle' },
      { word: 'decision', phonetic: '/dɪˈsɪʒn/', position: 'middle' },
      { word: 'treasure', phonetic: '/ˈtreʒər/', position: 'middle' },
    ],
  },
  {
    symbol: 'h',
    type: 'consonant',
    subtype: 'voiceless',
    name: '摩擦音 /h/',
    description: '气流从声门摩擦而出，声带不振动',
    mouthTip: '像哈气一样，轻轻送出气流',
    commonMistakes: ['气流太弱', '省略不发'],
    difficulty: 1,
    hardForChinese: false,
    confusableWith: ['f'],
    minimalPairs: {
      'f': [
        { word1: 'hat', phonetic1: '/hæt/', word2: 'fat', phonetic2: '/fæt/' },
        { word1: 'hair', phonetic1: '/heər/', word2: 'fair', phonetic2: '/feər/' },
        { word1: 'heat', phonetic1: '/hiːt/', word2: 'feet', phonetic2: '/fiːt/' },
        { word1: 'hill', phonetic1: '/hɪl/', word2: 'fill', phonetic2: '/fɪl/' },
        { word1: 'hear', phonetic1: '/hɪər/', word2: 'fear', phonetic2: '/fɪər/' },
      ],
    },
    words: [
      { word: 'hat', phonetic: '/hæt/', position: 'beginning' },
      { word: 'home', phonetic: '/həʊm/', position: 'beginning' },
      { word: 'happy', phonetic: '/ˈhæpi/', position: 'beginning' },
      { word: 'behind', phonetic: '/bɪˈhaɪnd/', position: 'middle' },
      { word: 'help', phonetic: '/help/', position: 'beginning' },
    ],
  },
];

const affricates: Phoneme[] = [
  {
    symbol: 'tʃ',
    type: 'consonant',
    subtype: 'voiceless',
    name: '塞擦音 /tʃ/',
    description: '先发/t/再发/ʃ/，快速连接，声带不振动',
    mouthTip: '舌尖抵住上牙龈，然后快速放开发"吃"的音',
    commonMistakes: ['两个音分得太开', '与/ʃ/混淆'],
    difficulty: 2,
    hardForChinese: false,
    confusableWith: ['dʒ', 'ʃ'],
    minimalPairs: {
      'dʒ': [
        { word1: 'chain', phonetic1: '/tʃeɪn/', word2: 'Jane', phonetic2: '/dʒeɪn/' },
        { word1: 'chunk', phonetic1: '/tʃʌŋk/', word2: 'junk', phonetic2: '/dʒʌŋk/' },
        { word1: 'cherry', phonetic1: '/ˈtʃeri/', word2: 'Jerry', phonetic2: '/ˈdʒeri/' },
        { word1: 'cheer', phonetic1: '/tʃɪər/', word2: 'jeer', phonetic2: '/dʒɪər/' },
        { word1: 'chin', phonetic1: '/tʃɪn/', word2: 'gin', phonetic2: '/dʒɪn/' },
        { word1: 'choke', phonetic1: '/tʃəʊk/', word2: 'joke', phonetic2: '/dʒəʊk/' },
        { word1: 'choose', phonetic1: '/tʃuːz/', word2: 'juice', phonetic2: '/dʒuːs/' },
        { word1: 'chew', phonetic1: '/tʃuː/', word2: 'Jew', phonetic2: '/dʒuː/' },
      ],
    },
    words: [
      { word: 'chair', phonetic: '/tʃeər/', position: 'beginning' },
      { word: 'watch', phonetic: '/wɒtʃ/', position: 'end' },
      { word: 'teacher', phonetic: '/ˈtiːtʃər/', position: 'middle' },
      { word: 'lunch', phonetic: '/lʌntʃ/', position: 'end' },
      { word: 'children', phonetic: '/ˈtʃɪldrən/', position: 'beginning' },
    ],
  },
  {
    symbol: 'dʒ',
    type: 'consonant',
    subtype: 'voiced',
    name: '塞擦音 /dʒ/',
    description: '先发/d/再发/ʒ/，快速连接，声带振动',
    mouthTip: '与/tʃ/相同动作，但声带振动',
    commonMistakes: ['与/tʃ/混淆', '声带振动不够'],
    difficulty: 2,
    hardForChinese: false,
    confusableWith: ['tʃ', 'ʒ'],
    minimalPairs: {
      'tʃ': [
        { word1: 'Jane', phonetic1: '/dʒeɪn/', word2: 'chain', phonetic2: '/tʃeɪn/' },
        { word1: 'junk', phonetic1: '/dʒʌŋk/', word2: 'chunk', phonetic2: '/tʃʌŋk/' },
        { word1: 'Jerry', phonetic1: '/ˈdʒeri/', word2: 'cherry', phonetic2: '/ˈtʃeri/' },
        { word1: 'jeer', phonetic1: '/dʒɪər/', word2: 'cheer', phonetic2: '/tʃɪər/' },
        { word1: 'gin', phonetic1: '/dʒɪn/', word2: 'chin', phonetic2: '/tʃɪn/' },
        { word1: 'joke', phonetic1: '/dʒəʊk/', word2: 'choke', phonetic2: '/tʃəʊk/' },
        { word1: 'juice', phonetic1: '/dʒuːs/', word2: 'choose', phonetic2: '/tʃuːz/' },
        { word1: 'Jew', phonetic1: '/dʒuː/', word2: 'chew', phonetic2: '/tʃuː/' },
      ],
    },
    words: [
      { word: 'job', phonetic: '/dʒɒb/', position: 'beginning' },
      { word: 'age', phonetic: '/eɪdʒ/', position: 'end' },
      { word: 'jump', phonetic: '/dʒʌmp/', position: 'beginning' },
      { word: 'enjoy', phonetic: '/ɪnˈdʒɔɪ/', position: 'middle' },
      { word: 'orange', phonetic: '/ˈɒrɪndʒ/', position: 'end' },
    ],
  },
];

const nasals: Phoneme[] = [
  {
    symbol: 'm',
    type: 'consonant',
    subtype: 'nasal',
    name: '鼻音 /m/',
    description: '双唇紧闭，气流从鼻腔流出，声带振动',
    mouthTip: '闭上嘴巴，发出"嗯"的鼻音',
    commonMistakes: ['嘴唇没有完全闭合', '鼻音不够明显'],
    difficulty: 1,
    hardForChinese: false,
    confusableWith: ['n'],
    minimalPairs: {
      'n': [
        { word1: 'met', phonetic1: '/met/', word2: 'net', phonetic2: '/net/' },
        { word1: 'map', phonetic1: '/mæp/', word2: 'nap', phonetic2: '/næp/' },
        { word1: 'might', phonetic1: '/maɪt/', word2: 'night', phonetic2: '/naɪt/' },
        { word1: 'mine', phonetic1: '/maɪn/', word2: 'nine', phonetic2: '/naɪn/' },
        { word1: 'sum', phonetic1: '/sʌm/', word2: 'sun', phonetic2: '/sʌn/' },
        { word1: 'meal', phonetic1: '/miːl/', word2: 'kneel', phonetic2: '/niːl/' },
        { word1: 'mail', phonetic1: '/meɪl/', word2: 'nail', phonetic2: '/neɪl/' },
        { word1: 'meat', phonetic1: '/miːt/', word2: 'neat', phonetic2: '/niːt/' },
      ],
    },
    words: [
      { word: 'man', phonetic: '/mæn/', position: 'beginning' },
      { word: 'time', phonetic: '/taɪm/', position: 'end' },
      { word: 'make', phonetic: '/meɪk/', position: 'beginning' },
      { word: 'family', phonetic: '/ˈfæməli/', position: 'middle' },
      { word: 'summer', phonetic: '/ˈsʌmər/', position: 'middle' },
    ],
  },
  {
    symbol: 'n',
    type: 'consonant',
    subtype: 'nasal',
    name: '鼻音 /n/',
    description: '舌尖抵上齿龈，气流从鼻腔流出，声带振动',
    mouthTip: '舌尖抵住上牙龈，发出鼻音',
    commonMistakes: ['舌位不准确', '与/m/混淆'],
    difficulty: 1,
    hardForChinese: false,
    confusableWith: ['ŋ'],
    minimalPairs: {
      'ŋ': [
        { word1: 'sin', phonetic1: '/sɪn/', word2: 'sing', phonetic2: '/sɪŋ/' },
        { word1: 'thin', phonetic1: '/θɪn/', word2: 'thing', phonetic2: '/θɪŋ/' },
        { word1: 'ban', phonetic1: '/bæn/', word2: 'bang', phonetic2: '/bæŋ/' },
        { word1: 'win', phonetic1: '/wɪn/', word2: 'wing', phonetic2: '/wɪŋ/' },
        { word1: 'run', phonetic1: '/rʌn/', word2: 'rung', phonetic2: '/rʌŋ/' },
        { word1: 'ton', phonetic1: '/tʌn/', word2: 'tongue', phonetic2: '/tʌŋ/' },
        { word1: 'sun', phonetic1: '/sʌn/', word2: 'sung', phonetic2: '/sʌŋ/' },
        { word1: 'ran', phonetic1: '/ræn/', word2: 'rang', phonetic2: '/ræŋ/' },
        { word1: 'fan', phonetic1: '/fæn/', word2: 'fang', phonetic2: '/fæŋ/' },
        { word1: 'pin', phonetic1: '/pɪn/', word2: 'ping', phonetic2: '/pɪŋ/' },
      ],
    },
    words: [
      { word: 'no', phonetic: '/nəʊ/', position: 'beginning' },
      { word: 'sun', phonetic: '/sʌn/', position: 'end' },
      { word: 'nice', phonetic: '/naɪs/', position: 'beginning' },
      { word: 'dinner', phonetic: '/ˈdɪnər/', position: 'middle' },
      { word: 'run', phonetic: '/rʌn/', position: 'end' },
    ],
  },
  {
    symbol: 'ŋ',
    type: 'consonant',
    subtype: 'nasal',
    name: '鼻音 /ŋ/',
    description: '舌后部抵软腭，气流从鼻腔流出，声带振动',
    mouthTip: '舌根抵住软腭，发出深沉的鼻音',
    commonMistakes: ['发成/n/+/ɡ/', '舌位不够后'],
    difficulty: 3,
    hardForChinese: true,
    confusableWith: ['n'],
    minimalPairs: {
      'n': [
        { word1: 'sing', phonetic1: '/sɪŋ/', word2: 'sin', phonetic2: '/sɪn/' },
        { word1: 'thing', phonetic1: '/θɪŋ/', word2: 'thin', phonetic2: '/θɪn/' },
        { word1: 'bang', phonetic1: '/bæŋ/', word2: 'ban', phonetic2: '/bæn/' },
        { word1: 'wing', phonetic1: '/wɪŋ/', word2: 'win', phonetic2: '/wɪn/' },
        { word1: 'rung', phonetic1: '/rʌŋ/', word2: 'run', phonetic2: '/rʌn/' },
        { word1: 'tongue', phonetic1: '/tʌŋ/', word2: 'ton', phonetic2: '/tʌn/' },
        { word1: 'sung', phonetic1: '/sʌŋ/', word2: 'sun', phonetic2: '/sʌn/' },
        { word1: 'rang', phonetic1: '/ræŋ/', word2: 'ran', phonetic2: '/ræn/' },
        { word1: 'fang', phonetic1: '/fæŋ/', word2: 'fan', phonetic2: '/fæn/' },
        { word1: 'ping', phonetic1: '/pɪŋ/', word2: 'pin', phonetic2: '/pɪn/' },
      ],
    },
    words: [
      { word: 'sing', phonetic: '/sɪŋ/', position: 'end' },
      { word: 'thing', phonetic: '/θɪŋ/', position: 'end' },
      { word: 'long', phonetic: '/lɒŋ/', position: 'end' },
      { word: 'morning', phonetic: '/ˈmɔːnɪŋ/', position: 'end' },
      { word: 'English', phonetic: '/ˈɪŋɡlɪʃ/', position: 'middle' },
    ],
  },
];

const liquidsAndGlides: Phoneme[] = [
  {
    symbol: 'l',
    type: 'consonant',
    subtype: 'liquid',
    name: '边音 /l/',
    description: '舌尖抵上齿龈，气流从舌两侧流出，声带振动',
    mouthTip: '舌尖抵住上牙龈，气流从舌头两边流出',
    commonMistakes: ['舌位不准', '与/r/混淆'],
    difficulty: 2,
    hardForChinese: true,
    confusableWith: ['r'],
    minimalPairs: {
      'r': [
        { word1: 'light', phonetic1: '/laɪt/', word2: 'right', phonetic2: '/raɪt/' },
        { word1: 'led', phonetic1: '/led/', word2: 'red', phonetic2: '/red/' },
        { word1: 'lack', phonetic1: '/læk/', word2: 'rack', phonetic2: '/ræk/' },
        { word1: 'long', phonetic1: '/lɒŋ/', word2: 'wrong', phonetic2: '/rɒŋ/' },
        { word1: 'law', phonetic1: '/lɔː/', word2: 'raw', phonetic2: '/rɔː/' },
        { word1: 'lake', phonetic1: '/leɪk/', word2: 'rake', phonetic2: '/reɪk/' },
        { word1: 'load', phonetic1: '/ləʊd/', word2: 'road', phonetic2: '/rəʊd/' },
        { word1: 'lock', phonetic1: '/lɒk/', word2: 'rock', phonetic2: '/rɒk/' },
        { word1: 'lip', phonetic1: '/lɪp/', word2: 'rip', phonetic2: '/rɪp/' },
        { word1: 'late', phonetic1: '/leɪt/', word2: 'rate', phonetic2: '/reɪt/' },
      ],
    },
    words: [
      { word: 'love', phonetic: '/lʌv/', position: 'beginning' },
      { word: 'all', phonetic: '/ɔːl/', position: 'end' },
      { word: 'like', phonetic: '/laɪk/', position: 'beginning' },
      { word: 'yellow', phonetic: '/ˈjeləʊ/', position: 'middle' },
      { word: 'little', phonetic: '/ˈlɪtl/', position: 'beginning' },
    ],
  },
  {
    symbol: 'r',
    type: 'consonant',
    subtype: 'liquid',
    name: '近音 /r/',
    description: '舌尖卷起靠近硬腭但不接触，声带振动',
    mouthTip: '舌尖向上卷起但不触碰任何地方',
    commonMistakes: ['与/l/混淆', '舌头卷得不够'],
    difficulty: 4,
    hardForChinese: true,
    confusableWith: ['l'],
    minimalPairs: {
      'l': [
        { word1: 'right', phonetic1: '/raɪt/', word2: 'light', phonetic2: '/laɪt/' },
        { word1: 'red', phonetic1: '/red/', word2: 'led', phonetic2: '/led/' },
        { word1: 'rack', phonetic1: '/ræk/', word2: 'lack', phonetic2: '/læk/' },
        { word1: 'wrong', phonetic1: '/rɒŋ/', word2: 'long', phonetic2: '/lɒŋ/' },
        { word1: 'raw', phonetic1: '/rɔː/', word2: 'law', phonetic2: '/lɔː/' },
        { word1: 'rake', phonetic1: '/reɪk/', word2: 'lake', phonetic2: '/leɪk/' },
        { word1: 'road', phonetic1: '/rəʊd/', word2: 'load', phonetic2: '/ləʊd/' },
        { word1: 'rock', phonetic1: '/rɒk/', word2: 'lock', phonetic2: '/lɒk/' },
        { word1: 'rip', phonetic1: '/rɪp/', word2: 'lip', phonetic2: '/lɪp/' },
        { word1: 'rate', phonetic1: '/reɪt/', word2: 'late', phonetic2: '/leɪt/' },
      ],
    },
    words: [
      { word: 'red', phonetic: '/red/', position: 'beginning' },
      { word: 'car', phonetic: '/kɑːr/', position: 'end' },
      { word: 'right', phonetic: '/raɪt/', position: 'beginning' },
      { word: 'very', phonetic: '/ˈveri/', position: 'middle' },
      { word: 'drink', phonetic: '/drɪŋk/', position: 'beginning' },
    ],
  },
  {
    symbol: 'w',
    type: 'consonant',
    subtype: 'glide',
    name: '半元音 /w/',
    description: '嘴唇紧圆前突，迅速滑向后面的元音，声带振动',
    mouthTip: '嘴唇收圆像吹口哨，然后快速放开',
    commonMistakes: ['与/v/混淆', '嘴唇不够圆'],
    difficulty: 2,
    hardForChinese: true,
    confusableWith: ['v'],
    minimalPairs: {
      'v': [
        { word1: 'wine', phonetic1: '/waɪn/', word2: 'vine', phonetic2: '/vaɪn/' },
        { word1: 'west', phonetic1: '/west/', word2: 'vest', phonetic2: '/vest/' },
        { word1: 'wet', phonetic1: '/wet/', word2: 'vet', phonetic2: '/vet/' },
        { word1: 'wail', phonetic1: '/weɪl/', word2: 'veil', phonetic2: '/veɪl/' },
        { word1: 'worse', phonetic1: '/wɜːs/', word2: 'verse', phonetic2: '/vɜːs/' },
        { word1: 'whale', phonetic1: '/weɪl/', word2: 'vale', phonetic2: '/veɪl/' },
        { word1: 'wow', phonetic1: '/waʊ/', word2: 'vow', phonetic2: '/vaʊ/' },
        { word1: 'we\'re', phonetic1: '/wɪər/', word2: 'veer', phonetic2: '/vɪər/' },
        { word1: 'went', phonetic1: '/went/', word2: 'vent', phonetic2: '/vent/' },
        { word1: 'wane', phonetic1: '/weɪn/', word2: 'vain', phonetic2: '/veɪn/' },
      ],
    },
    words: [
      { word: 'water', phonetic: '/ˈwɔːtər/', position: 'beginning' },
      { word: 'we', phonetic: '/wiː/', position: 'beginning' },
      { word: 'want', phonetic: '/wɒnt/', position: 'beginning' },
      { word: 'away', phonetic: '/əˈweɪ/', position: 'middle' },
      { word: 'quick', phonetic: '/kwɪk/', position: 'middle' },
    ],
  },
  {
    symbol: 'j',
    type: 'consonant',
    subtype: 'glide',
    name: '半元音 /j/',
    description: '舌面靠近硬腭，迅速滑向后面的元音，声带振动',
    mouthTip: '像发"一"的起始动作，然后快速滑向下一个音',
    commonMistakes: ['发成完整的/i/', '与/dʒ/混淆'],
    difficulty: 1,
    hardForChinese: false,
    confusableWith: ['dʒ'],
    minimalPairs: {
      'dʒ': [
        { word1: 'yet', phonetic1: '/jet/', word2: 'jet', phonetic2: '/dʒet/' },
        { word1: 'year', phonetic1: '/jɪər/', word2: 'jeer', phonetic2: '/dʒɪər/' },
        { word1: 'yam', phonetic1: '/jæm/', word2: 'jam', phonetic2: '/dʒæm/' },
        { word1: 'yell', phonetic1: '/jel/', word2: 'jell', phonetic2: '/dʒel/' },
        { word1: 'yoke', phonetic1: '/jəʊk/', word2: 'joke', phonetic2: '/dʒəʊk/' },
        { word1: 'yaw', phonetic1: '/jɔː/', word2: 'jaw', phonetic2: '/dʒɔː/' },
        { word1: 'you', phonetic1: '/juː/', word2: 'Jew', phonetic2: '/dʒuː/' },
        { word1: 'yes', phonetic1: '/jes/', word2: 'Jess', phonetic2: '/dʒes/' },
      ],
    },
    words: [
      { word: 'yes', phonetic: '/jes/', position: 'beginning' },
      { word: 'you', phonetic: '/juː/', position: 'beginning' },
      { word: 'year', phonetic: '/jɪər/', position: 'beginning' },
      { word: 'young', phonetic: '/jʌŋ/', position: 'beginning' },
      { word: 'yellow', phonetic: '/ˈjeləʊ/', position: 'beginning' },
    ],
  },
];

// ============================================================================
// 导出分类数据
// ============================================================================

export const phonemeCategories: PhonemeCategory[] = [
  {
    id: 'short-vowels',
    name: '短元音',
    description: '发音短促的元音，共7个',
    phonemes: shortVowels,
  },
  {
    id: 'long-vowels',
    name: '长元音',
    description: '发音延长的元音，共5个',
    phonemes: longVowels,
  },
  {
    id: 'diphthongs',
    name: '双元音',
    description: '由两个元音滑动组成，共8个',
    phonemes: diphthongs,
  },
  {
    id: 'plosives',
    name: '爆破音',
    description: '气流受阻后突然释放，共6个',
    phonemes: plosives,
  },
  {
    id: 'fricatives',
    name: '摩擦音',
    description: '气流通过窄缝摩擦发出，共9个',
    phonemes: fricatives,
  },
  {
    id: 'affricates',
    name: '塞擦音',
    description: '先阻塞再摩擦，共2个',
    phonemes: affricates,
  },
  {
    id: 'nasals',
    name: '鼻音',
    description: '气流从鼻腔流出，共3个',
    phonemes: nasals,
  },
  {
    id: 'liquids-glides',
    name: '流音与半元音',
    description: '边音、近音和半元音，共4个',
    phonemes: liquidsAndGlides,
  },
];
